// Generated by ChatGTP, modified by human

using System.Collections.Generic;

[System.Serializable]
public class Connection
{   // the target is the neuron which holds the Connection
    public Neuron source;
    public float weight;

    public Connection(Neuron source, float weight)
    {
        this.source = source;
        this.weight = weight;
    }
}