// Generated by ChatGTP.

[System.Serializable]
public class Layer
{
    public Neuron[] neurons;

    public Layer(int numNeurons, ActivationFunction? function = null)
    {
        neurons = new Neuron[numNeurons];
        for (int i = 0; i < numNeurons; i++)
        {
            neurons[i] = new Neuron(function);
        }
    }

    public void Evaluate()
    {
        foreach (var neuron in neurons)
        {
            neuron.Evaluate();
        }
    }
}