// Generated by ChatGTP, modified by human

using System;

[Serializable]
public class Path
{
    public readonly Neuron[] neurons;

    public Path(System.Collections.Generic.List<Neuron> neurons)
    {
        this.neurons = neurons.ToArray();
    }
}

[Serializable]
public class Neuron
{
    public float bias;
    //public Connection[] connections;
    public Neuron[] sources;
    public float[] weights;
    public ActivationFunction function;
    public float value;
    public bool dirty;
    public Path[] paths;

    public Neuron(ActivationFunction? function = null)
    {
        bias = UnityEngine.Random.Range(-1f, 1f);

        if (function == null)
        {
            this.function = ActivationFunction.Input;
        }
        else
        {
            this.function = UnityEngine.Random.Range(0, 1) == 0 ? ActivationFunction.Sigmoid : ActivationFunction.TanH;
        }
    }

    public void Evaluate()
    {
        float sum = bias;
        for (int i = 0; i < sources.Length; i++)
        {
            sum += weights[i] * sources[i].value;
        }
        value = Activation.Evaluate(function, sum);
        dirty = false;
    }
}